// <auto-generated />
namespace Invenio.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ReportDateOfInspection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReportDateOfInspection));
        
        string IMigrationMetadata.Id
        {
            get { return "201906251918060_ReportDateOfInspection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
